name: Update Sports Schedules

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6:00 UTC
  workflow_dispatch: # allows you to manually trigger it too

jobs:
  update-schedules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          SPORTSDB_API_KEY: ${{ secrets.SPORTSDB_API_KEY }}
        run: node index.js

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add games.json
          git commit -m "Update games.json [skip ci]" || echo "No changes to commit"
          git push